### ISSUE TITLE
Matcher map README bug and limitations

### ISSUE THREAD

**Issue by k7k0** [robert-nemet/klock#2]
If you apply the [Mandatory Locking README example](https://github.com/robert-nemet/klock/blob/main/README.md#mandatory-locking):

```
apiVersion: klock.rnemet.dev/v1
kind: Lock
metadata:
  name: lock-red-blue
  namespace: argocd
spec:
  operations:
    - UPDATE
    - DELETE
  matcher:
    aura: red
    aura: blue
```

Only `aura: blue` matcher will be created, as they are [defined as maps of string](https://github.com/robert-nemet/klock/blob/feb49ac35442ea96cf3f4114790b93321f4959b5/apis/klock/v1/lock_types.go#L31).

This could become a major limitation of the matching strategies as requires creating different Locks for matching appropriate resources. Would be really cool to be able to able to define those as arrays instead of maps, also in that way could grow in the future with operators (AND/OR)
